name: ClusterFuzzLite PR
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.clusterfuzzlite/**'
      - 'pyproject.toml'
      - 'uv.lock'

permissions:
  contents: read

jobs:
  PR:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: python
      - name: Run Fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          fuzz-seconds: 300


          mode: 'code-change'
