name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@0b932710ef31da3846e123d862731881525a855b # v5.3.0
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@885a382caedc210ca385994b5055b8979310c81d # v5.1.0

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Ruff
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Mypy
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest
